"""
Transliterate Cyrillic script by the ALA-LC (Library of Congress) rules
"""
def ala_lc(word):
    """
    Transliterate a word in Cyrillic script using the
    ALA-LC (Library of Congress) rules.
    """
    ala_lc_dict = {
        'Ё' : 'Ë',
        'А' : 'A',
        'Б' : 'B',
        'В' : 'V',
        'Г' : 'G',
        'Д' : 'D',
        'Е' : 'E',
        'Ж' : 'Zh',
        'З' : 'Z',
        'И' : 'I',
        'Й' : 'Ĭ',
        'К' : 'K',
        'Л' : 'L',
        'М' : 'M',
        'Н' : 'N',
        'О' : 'O',
        'П' : 'P',
        'Р' : 'R',
        'С' : 'S',
        'Т' : 'T',
        'У' : 'U',
        'Ф' : 'F',
        'Х' : 'Kh',
        'Ц' : 'T͡S',
        'Ч' : 'Ch',
        'Ш' : 'Sh',
        'Щ' : 'Shch',
        'Ъ' : 'ʺ',
        'Ы' : 'Y',
        'Ь' : 'ʹ',
        'Э' : 'Ė',
        'Ю' : 'I͡U',
        'Я' : 'I͡A',
        'а' : 'a',
        'б' : 'b',
        'в' : 'v',
        'г' : 'g',
        'д' : 'd',
        'е' : 'e',
        'ж' : 'zh',
        'з' : 'z',
        'и' : 'i',
        'й' : 'ĭ',
        'к' : 'k',
        'л' : 'l',
        'м' : 'm',
        'н' : 'n',
        'о' : 'o',
        'п' : 'p',
        'р' : 'r',
        'с' : 's',
        'т' : 't',
        'у' : 'u',
        'ф' : 'f',
        'х' : 'kh',
        'ц' : 't͡s',
        'ч' : 'ch',
        'ш' : 'sh',
        'щ' : 'shch',
        'ъ' : 'ʺ',
        'ы' : 'y',
        'ь' : 'ʹ',
        'э' : 'ė',
        'ю' : 'i͡u',
        'я' : 'i͡a',
        'ё' : 'ë',}
    return "".join(ala_lc_dict.get(c, c) for c in word)
